Repository golang-cafe/job-board, pull requests merged in 2023-04, with the labels that each got.

#84 Bug fix/image crop
  .gitignore
  cmd/server/main.go
  go.mod
  go.sum
  internal/handler/handlers.go
  run-local-webserver.sh
  setup-database.sh
  static/views/edit-developer-profile.html
  static/views/edit.html
  static/views/manage.html
Labels: under-review

#90 [BUG] Remove https in Local Environment Logs
  internal/config/config.go
  internal/handler/handlers.go
Labels: under-review

#94 [Bug Fix] Redirect logged users when visiting "join community" page
  internal/handler/handlers.go
Labels: in-progress

#98 [FEATURE] add created_at field to user_sign_on_token table/add expired tokens cronjob #93
  cmd/server/main.go
  internal/handler/handlers.go
  internal/user/repository.go
  latest-schema.sql
Labels: changes-requested

#77 [FEATURE] add developer metadata table and endpoint
  cmd/server/main.go
  internal/developer/model.go
  internal/developer/repository.go
  internal/handler/handlers.go
  latest-schema.sql
  static/views/edit-developer-profile.html
  static/views/view-developer-profile.html
Labels: changes-requested

#109 [BUG] W3C validation fix validation v2
  static/views/apply-message.html
  static/views/companies.html
  static/views/developers.html
  static/views/edit.html
  static/views/job.html
  static/views/list-jobs-admin.html
  static/views/newsletter.html
  static/views/post-a-job-success.html
  static/views/salary-explorer.html
  static/views/terms-of-service.html
  static/views/view-developer-profile.html
Labels: under-review

#111 [FEATURE] Show applicants on edit and manage job pages
  cmd/server/main.go
  internal/handler/handlers.go
  internal/job/model.go
  internal/job/repository.go
  static/views/edit.html
  static/views/manage.html
Labels: under-review
